### ISSUE TITLE
test release 1.4, SMS Messages not working

### ISSUE THREAD

**Issue by hoclun-rigsep** [Inokinoki/kde-blog#4]
Nothing appears to happen when I click this from the tray icon dropdown.

**Comment by Inokinoki** [comment]
Yes, it doesn't work at the moment.

I'm still testing it due to a bug associated with QML apps.

**Comment by Inokinoki** [comment]
You could try this release:
https://github.com/Inokinoki/kde-blog/releases/tag/20190901

The QCA framework prevents it from packaging QML apps. The one `kdeconnect-indicator-no-qca.zip` without QCA including SMS app, SFTP Browser app, etc.
