### ISSUE TITLE
No tray icon visible

### ISSUE THREAD

**Issue by deftdawg** [Inokinoki/kde-blog#5]
When I started KDE indicator, I thought the app didn't work initially... after allowing it to run, I didn't see anything.  I clicked next to the tray and that's when I saw it was actually running. 

Thanks for your great work, btw. 

**Version:** Using last successful build from [here](https://binary-factory.kde.org/view/MacOS/job/kdeconnect-kde_Release_macos/) dated April 17th, 2020.

![Screen Shot 2020-04-18 at 9 40 03 PM](https://user-images.githubusercontent.com/4991612/79677241-2bb05580-81bd-11ea-8139-b4ec5084a350.png)
![Screen Shot 2020-04-18 at 9 40 58 PM](https://user-images.githubusercontent.com/4991612/79677255-4d114180-81bd-11ea-8e32-f6bacd9e2a6c.png)

![Screen Shot 2020-04-18 at 9 42 40 PM](https://user-images.githubusercontent.com/4991612/79677272-88ac0b80-81bd-11ea-84a4-1734cdff933a.png)

**Comment by Inokinoki** [comment]
It's been fixed last week. You could use Nightly Build: https://binary-factory.kde.org/view/MacOS/job/kdeconnect-kde_Nightly_macos/

**Comment by deftdawg** [comment]
Unfortunately, the nightly builds have been broken since last week. 😢 
![Screen Shot 2020-04-22 at 9 36 18 PM](https://user-images.githubusercontent.com/4991612/80049581-4f3b0f00-84e1-11ea-8f36-3b86322404b1.png)

**Comment by Inokinoki** [comment]
The latest successful one is ok 😋

**Comment by deftdawg** [comment]
EDIT: Nevermind my bad...  I tried it again and it started though it's still a bit wonky in that, I had to kill it and restart it to get it working and the App icon is missing.   But tray icon is there for me now.  Thanks.

```
ps -ef | grep kde
  501  6523     1   0  1:01pm ??         0:00.61 /Applications/kdeconnect-indicator.app/Contents/MacOS/kdeconnectd
  501  6527  6523   0  1:01pm ??         0:00.01 /Applications/kdeconnect-indicator.app/Contents/MacOS/dbus-daemon --print-address --nofork --config-file=/Applications/kdeconnect-indicator.app/Contents/Resources/dbus-1/session.conf --address=unix:tmpdir=/tmp
  501  6543   549   0  1:02pm ttys003    0:00.01 grep kde

kill 6523 6527
# relaunch
# d-bus waiting message and it works
ps -ef | grep kde
  501  6570     1   0  1:03pm ??         0:00.55 /Applications/kdeconnect-indicator.app/Contents/MacOS/kdeconnect-indicator
  501  6573     1   0  1:03pm ??         0:00.47 /Applications/kdeconnect-indicator.app/Contents/MacOS/kdeconnectd
  501  6575  6573   0  1:03pm ??         0:00.01 /Applications/kdeconnect-indicator.app/Contents/MacOS/dbus-daemon --print-address --nofork --config-file=/Applications/kdeconnect-indicator.app/Contents/Resources/dbus-1/session.conf --address=unix:tmpdir=/tmp
  501  6583   549   0  1:04pm ttys003    0:00.00 grep kde
```

![Screen Shot 2020-04-23 at 1 05 45 PM](https://user-images.githubusercontent.com/4991612/80128043-25c2c780-8563-11ea-8ba0-7eda6b45c315.png)


![Screen Shot 2020-04-23 at 1 08 12 PM](https://user-images.githubusercontent.com/4991612/80128327-7d613300-8563-11ea-9606-63b42a398195.png)

**Comment by deftdawg** [comment]
Of course no sooner do I write that, I realize what's going on... 

Start up looks like this (good):
![Screen Shot 2020-04-23 at 1 14 07 PM](https://user-images.githubusercontent.com/4991612/80128905-56efc780-8564-11ea-93db-a0c69daef818.png)

First click, also good... 
![Screen Shot 2020-04-23 at 1 14 33 PM](https://user-images.githubusercontent.com/4991612/80128931-6111c600-8564-11ea-9bc1-775aee9d3cbc.png)

Connect my phone and the icon turns into this:
![Screen Shot 2020-04-23 at 1 16 11 PM](https://user-images.githubusercontent.com/4991612/80129100-9b7b6300-8564-11ea-897c-6803fd34d612.png)

It's virtually invisible...  but still there.   Any chance could use a different icon that is darker when the phone connects, it makes it harder to see the icon when one would actually want to use it.  

Logically, it seems reversed of the behaviour of what one would be expected on OSX (notice the globe icon for VPN that I have next to it which is greyed-out to indicated the VPN is disabled).

**Comment by Inokinoki** [comment]
Yes, you're right.
On macOS it's better to reverse them.

You can try to use Homebrew to build this one from head:
https://github.com/Inokinoki/kdeconnect-kde-homebrew
I'm working on this repo to support Homebrew.

**Comment by boyuanx** [comment]
@Inokinoki Bumping this because the tray icon is again nowhere to be seen in both the nightly and stable builds. I know it's running because my phone still connects to my Mac and I can see it in Activity Monitor.

I first tried using your version but it randomly disconnects my phone. I then downloaded the nightly build and while it now connects to my phone instantly every single time and I was able to send files from the phone to my Mac, the tray icon is nowhere to be seen (not even transparent as I tried clicking everywhere). It does not seem to be a configuration issue either as I tried creating a new account and ran the nightly build, still not tray icon at all.

M1 MacBook Air w/ macOS 11.2.3

**Comment by Inokinoki** [comment]
> @Inokinoki Bumping this because the tray icon is again nowhere to be seen in both the nightly and stable builds. I know it's running because my phone still connects to my Mac and I can see it in Activity Monitor.
> 
> I first tried using your version but it randomly disconnects my phone. I then downloaded the nightly build and while it now connects to my phone instantly every single time and I was able to send files from the phone to my Mac, the tray icon is nowhere to be seen (not even transparent as I tried clicking everywhere). It does not seem to be a configuration issue either as I tried creating a new account and ran the nightly build, still not tray icon at all.
> 
> M1 MacBook Air w/ macOS 11.2.3

Wow, cool if this version can instantly connect to your phone.

I suggest copying the icon files from the previous workable app bundle into your build one. (As a workaround)

The icon stuff is all about the missing resource files during packing period, which is an issue of Craft.

Last time I fixed it with a workaround configuration in kdeconnect codebase. Still need investigation this time, will do it later.

**Comment by boyuanx** [comment]
> > @Inokinoki Bumping this because the tray icon is again nowhere to be seen in both the nightly and stable builds. I know it's running because my phone still connects to my Mac and I can see it in Activity Monitor.
> > I first tried using your version but it randomly disconnects my phone. I then downloaded the nightly build and while it now connects to my phone instantly every single time and I was able to send files from the phone to my Mac, the tray icon is nowhere to be seen (not even transparent as I tried clicking everywhere). It does not seem to be a configuration issue either as I tried creating a new account and ran the nightly build, still not tray icon at all.
> > M1 MacBook Air w/ macOS 11.2.3
> 
> Wow, cool if this version can instantly connect to your phone.
> 
> I suggest copying the icon files from the previous workable app bundle into your build one. (As a workaround)
> 
> The icon stuff is all about the missing resource files during packing period, which is an issue of Craft.
> 
> Last time I fixed it with a workaround configuration in kdeconnect codebase. Still need investigation this time, will do it later.

Thank you for the reply! Could you clarify which files inside the application bundle am I meant to copy? I looked under Resources and copied over some icon files but it didn't seem to help.

Also it might be worth mentioning I cannot run Craft locally as it gives me the following error when I try to run the `source` command: `unset_env:unset:8: : invalid parameter name`

Thanks again!
