### ISSUE TITLE
Consider creating a Homebrew Cask to make installation easier

### ISSUE THREAD

**Issue by deftdawg** [Inokinoki/kde-blog#6]
A lot of people probably don't know that KDE Connect Indicator is available for OSX...  It's really awesome for android phone users.  

You might want to consider making a [homebrew](https://brew.sh) Cask to make installation super easy... 

Once built a user with brew installed could execute something like this from the `Terminal`:
```sh
brew cask install kdeconnect-indicator
```

**Comment by Inokinoki** [comment]
Thanks!

I'm creating one suitable for HomeBrew here: https://github.com/Inokinoki/kdeconnect-kde-homebrew
And soon it can be installed via [HomeBrew KDE](https://github.com/KDE-mac/homebrew-kde)

**Comment by Inokinoki** [comment]
I've created a HomeBrew Cask receipt.

https://github.com/Homebrew/homebrew-cask/pull/85430#issuecomment-653943212

But it's rejected.

Anyway, I appended it to the release:
https://github.com/Inokinoki/kde-blog/releases/tag/20190901
